name: Build & Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: ソースコードを取得
        uses: actions/checkout@v3

      - name: ソースコードをローカルフォルダにコピー
        shell: cmd
        run: |
          echo ソースを D:\Project\demo_dev にコピー中...
          xcopy /E /Y . D:\Project\demo_dev

      - name: アプリケーションをビルド
        shell: cmd
        run: call D:\Project\demo_dev\build.bat

      - name: IIS サイトを停止
        shell: powershell
        run: |
          Write-Host "IIS サイトを停止中..."
          Stop-WebSite -Name 'demo'

      - name: デプロイ（ファイルをコピー）
        shell: cmd
        run: |
          echo ファイルをIISサイトにコピー中...
          xcopy /E /Y D:\Project\demo_dev\* "C:\inetpub\osafw-asp.net-master\www"

      - name: IIS サイトを開始
        shell: powershell
        run: |
          Write-Host "IIS サイトを起動中..."
          Start-WebSite -Name 'demo'

      - name: デプロイ完了確認（HTTPステータスチェック）
        shell: powershell
        run: powershell -ExecutionPolicy Bypass -File ./scripts/check-deploy.ps1

      - name: テストツール実行
        shell: cmd
        run: call C:\CAC\PoiTest.bat
