name: Build & Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # ローカルPCのセルフホストランナーを使う

    steps:
      - name: ソースコードを取得
        uses: actions/checkout@v3

      - name: ソースコードをローカルフォルダにコピー
        run: |
          echo ソースを D:\Project\demo にコピー中...
          xcopy /E /Y . D:\Project\demo

      - name: アプリケーションをビルド
        run: |
          call D:\Project\demo\build.bat

      - name: IIS サイトを停止
        run: |
          echo IIS サイトを停止中...
          powershell.exe -Command "Stop-WebSite -Name 'demo'"

      - name: デプロイ（ファイルをコピー）
        run: |
          echo ファイルをIISサイトにコピー中...
          xcopy /E /Y D:\Project\demo\* "C:\inetpub\osafw-asp.net-master\www"

      - name: IIS サイトを開始
        run: |
          echo IIS サイトを起動中...
          powershell.exe -Command "Start-WebSite -Name 'demo'"

      - name: デプロイ完了確認（HTTPステータスチェック）
        run: |
          echo デプロイ完了確認中...
          powershell -Command "
            $maxRetries = 10
            $url = 'http://localhost/'
            for ($i = 0; $i -lt $maxRetries; $i++) {
              try {
                $res = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 5
                if ($res.StatusCode -eq 200) {
                  Write-Host 'サイトが正常に応答しています。'
                  exit 0
                }
              } catch {
                Write-Host '応答なし、再試行します...'
              }
              Start-Sleep -Seconds 5
            }
            Write-Error 'デプロイ確認に失敗しました。'
            exit 1
          "

      - name: テストツール実行
        run: |
          echo テストツールを実行中...
          call C:\CAC\PoiTest.bat
